#ifndef RFM95W_LORA_DEFINES_H
#define RFM95W_LORA_DEFINES_H

#include <stdint.h>

typedef enum{
  RFM95W_LORA_REG_FIFIO = 0x00,
  RFM95W_LORA_REG_OP_MODE,

  RFM95W_LORA_REG_FRF_MSB = 0x06,
  RFM95W_LORA_REG_FRF_MID,
  RFM95W_LORA_REG_FRF_LSB,

  RFM95W_LORA_REG_PA_CONFIG,
  RFM95W_LORA_REG_PA_RAMP,

  RFM95W_LORA_REG_OCP,
  RFM95W_LORA_REG_LNA,

  RFM95W_LORA_REG_FIFO_ADDR_PTR,
  RFM95W_LORA_REG_FIFO_TX_BASE_ADDR,

  RFM95W_LORA_REG_IRQ_FLAGS,
  RFM95W_LORA_REG_IRQ_FLAGS_MASK,

  RFM95W_LORA_REG_FREQ_IF_MSB,
  RFM95W_LORA_REG_FREQ_IF_LSB,

  RFM95W_LORA_REG_SYMB_TIMEOUT_MSB,
  RFM95W_LORA_REG_SYMB_TIMEOUT_LSB,

  RFM95W_LORA_REG_TX_CFG,
  RFM95W_LORA_REG_PAYLOAD_LENGTH,

  RFM95W_LORA_REG_PREAMBLE_MSB,
  RFM95W_LORA_REG_PREAMBLE_LSB,

  RFM95W_LORA_REG_MODULATION_CFG,

  RFM95W_LORA_REG_RF_MODE,

  RFM95W_LORA_REG_HOP_PERIOD,

  RFM95W_LORA_REG_NB_RX_BYTES,

  RFM95W_LORA_REG_RX_HEADER_INFO,
  RFM95W_LORA_REG_RX_HEADER_CNT_VALUE,
  RFM95W_LORA_REG_RX_PACKET_CNT_VALUE,

  RFM95W_LORA_REG_MODEM_STAT,

  RFM95W_LORA_REG_PKT_SNR_VALUE,

  RFM95W_LORA_REG_RSSI_VALUE,
  RFM95W_LORA_REG_PKT_RSSI_VALUE,

  RFM95W_LORA_REG_HOP_CHANNEL,

  RFM95W_LORA_REG_RX_DATA_ADDR,

  RFM95W_LORA_REG_DIO_MAPPING1 = 0x40,
  RFM95W_LORA_REG_DIO_MAPPING2,

  RFM95W_LORA_REG_VERSION,

  RFM95W_LORA_REG_TCXO = 0x44,

  RFM95W_LORA_REG_PA_DAC,

  RFM95W_LORA_REG_FORMER_TEMP,

  RFM95W_LORA_REG_AGC_REF = 0x61,
  RFM95W_LORA_REG_AGC_THRESH1,
  RFM95W_LORA_REG_AGC_THRESH2,
  RFM95W_LORA_REG_AGC_THRESH3,
}RFM95W_LORA_REG_ADDR;

typedef enum{
  RFM95W_LORA_MODE_SLEEP = 0x00,
  RFM95W_LORA_MODE_STDBY,
  RFM95W_LORA_MODE_FSTX,
  RFM95W_LORA_MODE_TX,
  RFM95W_LORA_MODE_FSRX,
  RFM95W_LORA_MODE_RXCONTINUOS,
  RFM95W_LORA_MODE_RXSINGLE,
  RFM95W_LORA_MODE_CAD,
}RFM95W_LORA_MODE;

#define RFM95W_LORA_LORA_MODE 0x01
#define RFM95W_LORA_FSK_MODE  0x00

#define RFM95W_LORA_LOW_FREQ_MODE   0x01
#define RFM95W_LORA_HIHG_GREQ_MODE  0x00

#endif /* RFM95W_LORA_DEFINES_H */
