#ifndef RFW95W_DRIVER_H
#define RFW95W_DRIVER_H

typedef enum{
  RFW95W_LORA_REG_FIFIO = 0x00,
  RFW95W_LORA_REG_OP_MODE,

  RFW95W_LORA_REG_FRF_MSB = 0x06,
  RFW95W_LORA_REG_FRF_MID,
  RFW95W_LORA_REG_FRF_LSB,

  RFW95W_LORA_REG_PA_CONFIG,
  RFW95W_LORA_REG_PA_RAMP,

  RFW95W_LORA_REG_OCP,
  RFW95W_LORA_REG_LNA,

  RFW95W_LORA_REG_FIFO_ADDR_PTR,
  RFW95W_LORA_REG_FIFO_TX_BASE_ADDR,

  RFW95W_LORA_REG_IRQ_FLAGS,
  RFW95W_LORA_REG_IRQ_FLAGS_MASK,

  RFW95W_LORA_REG_FREQ_IF_MSB,
  RFW95W_LORA_REG_FREQ_IF_LSB,

  RFW95W_LORA_REG_SYMB_TIMEOUT_MSB,
  RFW95W_LORA_REG_SYMB_TIMEOUT_LSB,

  RFW95W_LORA_REG_TX_CFG,
  RFW95W_LORA_REG_PAYLOAD_LENGTH,

  RFW95W_LORA_REG_PREAMBLE_MSB,
  RFW95W_LORA_REG_PREAMBLE_LSB,

  RFW95W_LORA_REG_MODULATION_CFG,

  RFW95W_LORA_REG_RF_MODE,

  RFW95W_LORA_REG_HOP_PERIOD,

  RFW95W_LORA_REG_NB_RX_BYTES,

  RFW95W_LORA_REG_RX_HEADER_INFO,
  RFW95W_LORA_REG_RX_HEADER_CNT_VALUE,
  RFW95W_LORA_REG_RX_PACKET_CNT_VALUE,

  RFW95W_LORA_REG_MODEM_STAT,

  RFW95W_LORA_REG_PKT_SNR_VALUE,

  RFW95W_LORA_REG_RSSI_VALUE,
  RFW95W_LORA_REG_PKT_RSSI_VALUE,

  RFW95W_LORA_REG_HOP_CHANNEL,

  RFW95W_LORA_REG_RX_DATA_ADDR,

  RFW95W_LORA_REG_DIO_MAPPING1 = 0x40,
  RFW95W_LORA_REG_DIO_MAPPING2,

  RFW95W_LORA_REG_VERSION,

  RFW95W_LORA_REG_TCXO = 0x44,

  RFW95W_LORA_REG_PA_DAC,

  RFW95W_LORA_REG_FORMER_TEMP,

  RFW95W_LORA_REG_AGC_REF = 0x61,
  RFW95W_LORA_REG_AGC_THRESH1,
  RFW95W_LORA_REG_AGC_THRESH2,
  RFW95W_LORA_REG_AGC_THRESH3,
}RFW95W_LORA_REG_ADDR;




#endif /* RFW95W_DRIVER_H */
